### ISSUE TITLE
"duration" column different in Firefly and Hub

### ISSUE THREAD

**Issue by quentinmit** [immstudios/nebula#7]
I added `duration` to a view's columns. In Firefly it properly displays the duration, taking into account in and out marks, as a timecode. In Hub, though, it just displays the raw duration of the source file (not using in/out).

**Comment by martastain** [comment]
Hotfixed in https://github.com/immstudios/nebula-hub/commit/a2821697f7e69263006e2f83ddf3722548981409 

I should unify trimmed clips and assets containing subclips highlighting with Firefly. Also it is not possible to sort by the resulting duration, so the order may be wrong.
